package com.w11k.lsql.dialects;

import com.w11k.lsql.LSql;

import java.sql.PreparedStatement;

public class DB2Dialect extends GenericDialect {

    private class DB2StatementCreator extends StatementCreator {
        @Override
        public PreparedStatement createPreparedStatement(LSql lSql, String sqlString, boolean returnAutoGeneratedKeys) {
            sqlString = sqlString == null ? "" : sqlString.trim();
            if (sqlString.endsWith(";")) {
                sqlString = sqlString.substring(0, sqlString.length() - 1);
            }
            return super.createPreparedStatement(lSql, sqlString, returnAutoGeneratedKeys);
        }
    }

    @Override
    public StatementCreator getStatementCreator() {
        return new DB2StatementCreator();
    }
}
